- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/EthereumKit.kt
> Improve syncing logic for ethereum and erc20 tokens

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/BaseAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/TransactionRecord.kt
- ethereumkit/schemas/io.horizontalsystems.ethereumkit.core.storage.KitDatabase/2.json
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/KitDatabase.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/RoomStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/TransactionDao.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/EthereumTransaction.kt
Fix filtering Ethereum transactions from Token transactions
> Fix transactions filtering by input

- ethereumkit/src/androidTest/java/io/horizontalsystems/ethereumkit/light/core/storage/SpvRoomStorageTest.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/ApiDatabase.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/ApiRoomStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/light/core/SpvBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/light/core/storage/BlockHeaderDao.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/light/core/storage/RoomTypeConverters.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/light/core/storage/SpvDatabase.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/light/core/storage/SpvRoomStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/light/core/storage/TransactionDao.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/light/models/BlockHeader.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/light/net/PeerGroup.kt
> Save headers into Room

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvRoomStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/PeerGroup.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/connection/PeerConnection.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/DevP2PPeer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/messages/HelloMessage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/messages/StatusMessage.kt
- Add peer validation
- Pass PeerGroup to SpvBlockchain via constructor, make class names camel case
- Replace redundant while-loop in PeerConnection
> Improvements

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/MessageFactory.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/connection/PeerConnection.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/DevP2PPeer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeer.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/DevP2PPeerTest.kt
> Cover DevP2PPeer with unit tests

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/MainViewModel.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/SendReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/BaseAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/TransactionRecord.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_send_receive.xml
- app/src/main/res/values/colors.xml
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/ApiDatabase.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/ApiRoomStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/GasPriceDao.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/FeePriority.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/GasPrice.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/ApiGasPrice.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/EthereumKitTest.kt
> Custom gas price implementation

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/Extensions.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/CapabilityHelper.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/MaxCost.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/messages/StatusMessage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/rlp/RLP.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/spv/net/connection/FrameCodecTest.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/CapabilityHelperTest.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeerTest.kt
- Add tests for CapabilityHelper
> Parse flow control variables from StatusMessage

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/PeerGroup.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/messages/BlockHeadersMessage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/messages/GetBlockHeadersMessage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/messages/StatusMessage.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeerTest.kt
> Handle announced block headers in PeerGroup 

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/Extensions.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvRoomStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/TransactionSigner.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/room/AccountStateDao.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/room/SPVDatabase.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/room/TransactionDao.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/models/AccountState.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/models/RawTransaction.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/models/Signature.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/IPeer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/PeerGroup.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/connection/FrameCodec.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/messages/BlockHeadersMessage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/messages/SendTransactionMessage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/messages/TransactionStatusMessage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/rlp/RLP.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/EthereumKitTest.kt
- Fix bug in FrameCodec: read from input stream until whole frame is received
- Move storage related functionality from EthereumKit to IBlockchain
- Save account state to database
- Implement send transction
Close #54
> Implement sending transaction

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/TransactionsFragment.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/TransactionRecord.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- ethereumkit/src/androidTest/java/io/horizontalsystems/ethereumkit/spv/core/room/SpvRoomStorageTest.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionSigner.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/INetwork.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/MainNet.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/Ropsten.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/BlockHelper.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/PeerProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeer.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeerTest.kt
- Add method to EthereumKit to create instance using mnemonic words
- Fix typo in TransactionRecord
- Change type of gasPrice to Long
- Add MainNet configuration and move INetwork to EthereumKit
> Minor changes

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20DatabaseManager.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumDatabaseManager.kt
- Refactor database names
- Increase gas limit to 150,000
Close #68
> Enhancements

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/MainViewModel.kt
- ethereumkit/build.gradle
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/RpcApiProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/InfuraService.kt
- Add basic authentication to Infura service
- Change version name
> Infura auth

- app/build.gradle
- app/src/main/assets/logback.xml
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/MainViewModel.kt
- ethereumkit/build.gradle
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/geth/GethBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/BlockSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/PeerGroup.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/PeerProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/connection/Connection.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/connection/FrameCodec.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/DevP2PConnection.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/DevP2PPeer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeer.kt
- Add slf4j logger
- Set listener to peer in PeerGroup
Close #79
> Add slf4j logger

- erc20kit/build.gradle
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/TransactionManager.kt
- ethereumkit/build.gradle
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Extensions.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/geth/GethBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/rlp/RLP.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/spv/net/les/LESPeerTest.kt
- geth-android/build.gradle
- settings.gradle
- Include geth mobile aar as a module 
- Fix RLP encoding of a long value
Close #82
> Include geth mobile as a module

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/TransactionsFragment.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Extensions.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/EtherscanService.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/InfuraService.kt
- Fix bug in long to byte array conversion
- Add loggers for EtherscanService and InfuraService
- Set EthereumKit as listener to TransactionManager
> Minor enhancements & bug fixes

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/MainViewModel.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20DatabaseManager.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumDatabaseManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
> Clear DB based on walletId

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/InfuraRpcApiProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/RpcApiProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionsProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- add interface ITransactionManager
- add field source to IBlockchain, IRpcApiProvider interfaces
- rename RpcApiProvider to InfuraRpcApiProvider
> Add statusInfo() method to EthereumKit

- ethereumkit/src/main/AndroidManifest.xml
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/ConnectionManager.kt
- listen to connectivity and start sync when network is available
> Add ConnectionManager to ApiBlockchain

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/MainViewModel.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/IAdapter.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/DataProvider.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Interfaces.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/TransactionManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/InfuraRpcApiProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/InfuraService.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- Refactor return parameter of estimateGas method to Long
- Add additional gasPrice parameter to estimateGas method
> - Refactor estimateGas method input and return parameter types

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/models/ValidationError.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/models/ApiError.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/InfuraService.kt
- Handle Infura RPC-API errors
- Handle validation errors in ERC20 kit
> Handle Infura RPC-API and ERC20 Validation errors

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/DataProvider.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Interfaces.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/TransactionManager.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/models/TokenError.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/models/Transaction.kt
- erc20kit/src/test/java/io/horizontalsystems/erc20kit/core/DataProviderTest.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/InfuraRpcApiProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/TransactionStatus.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/ValidationError.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/InfuraService.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- Handle ETH and ERC20 transaction statuses
> Handle ETH and ERC20 transaction statuses

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/TransactionRecord.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/models/TransactionInfo.kt
- Fix ERC20 transaction status handler
- Update demo App adapters
> Fix ERC20 transaction status handler

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/room/Erc20KitDatabase.kt
> Upgrade db version

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/MainViewModel.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- rpcApi parameter can be Infura or Incubed
- update in3-c submodule to v2.3.0
> Add rpcApi type parameter to EthereumKit.getInstance()

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/EthereumAdapter.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/AddressValidator.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/test/java/io/horizontalsystems/ethereumkit/core/AddressValidatorTest.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2300
> Convert Address validation method to static

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/IncubedRpcApiProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/InfuraRpcApiProvider.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2334
> Fix gas estimation by provider Incubed

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/ApiBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/ConnectionManager.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2436
> Fix connectivity manager 

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/ConnectionManager.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2436
> Subscribe to network events on app resume and unsubscribe on pause

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionManager.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2484
> Filter empty Ethereum transactions on sending Erc20 tokens

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Interfaces.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/TransactionManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/RpcBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/WebSocketRpcSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/models/EthereumKitState.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionManager.kt
> Refresh Ethereum/Erc20 transactions when balance/nonce is updated

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/jsonrpc/JsonRpc.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2983
> Handle Infura Rpc insufficient balance errors

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/jsonrpc/JsonRpc.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3037
> Add new cause for Rpc error InsufficientBalance

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20TransactionSyncer.kt
- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/TransactionManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/core/InfuraRpcWebSocket.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/core/WebSocketRpcSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/AbstractTransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/EthereumTransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/InternalTransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/PendingTransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionSyncManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionSyncer.kt
- stop transaction syncer, clear rx subscriptions
- in WebSocketRpcSyncer don't start syncing after socket connection
> Properly handle stopping kits

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/TransactionDao.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/TransactionDatabase.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/DroppedTransaction.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/FullTransaction.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/PendingTransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionSyncManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionSyncer.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3136
> Bug fixes and enhancements

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20Kit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/EtherscanService.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3258
> Use single retrofit client for Erc20 tokens

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/contract/Eip20ContractMethodFactories.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/jsonrpc/JsonRpc.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/contracts/ContractMethodFactories.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/contract/SwapContractMethodFactories.kt
- Remove handling of InsufficientBalance error
> Refactor contract method factory classes

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/MainViewModel.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- pass mnemonic seed for getting instance of EthereumKit
> Add ability to get Ethereum address private key

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
that accept words and passphrase instead of seed.
> Add convenience methods for address() and privateKey()

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/EtherscanService.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/TokenFactory.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/TradeManager.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/models/Pair.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3819
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2812
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2953
> Testnet support

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/TransactionDao.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/PendingTransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionSyncer.kt
> Fix fail tx behavior

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/Configuration.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/Erc20Adapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/Erc20BaseAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/EthereumAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/core/EthereumBaseAdapter.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/addresswatch/AddressWatchActivity.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/addresswatch/AddressWatchViewModel.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/BalanceFragment.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/MainActivity.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/MainViewModel.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/SendReceiveFragment.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/SwapFragment.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/TransactionsFragment.kt
- app/src/main/res/layout/activity_address_watch.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/menu/main_menu.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/core/RpcBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionBuilder.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/signer/EthSigner.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/signer/Signer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/SpvBlockchain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/core/TransactionSender.kt
ref https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4403
> Implement address watch

- app/build.gradle
- app/src/main/AndroidManifest.xml
- build.gradle
- erc20kit/build.gradle
- ethereumkit/build.gradle
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/spv/net/devp2p/DevP2PConnection.kt
- gradle/wrapper/gradle-wrapper.properties
- oneinchkit/build.gradle
- uniswapkit/build.gradle
- Remove jcenter
- Set Java version to 11
> Update libraries to latest versions

- app/build.gradle
- erc20kit/build.gradle
- ethereumkit/build.gradle
- oneinchkit/build.gradle
- uniswapkit/build.gradle
- Set JvmTarget in all submodules to Java 11
> Fix publishing submodules by Maven

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/api/core/NodeApiProvider.kt
otherwise, exceptions thrown in rpc.parseResponse are wrapped to RuntimeException
> Parse rpc response outside of rx.map operator

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/RpcSource.kt
- gradle/wrapper/gradle-wrapper.properties
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4734
> Add new BinanceSmartChain RPC provider

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/ConnectionManager.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4819
> Remove connection state reset on app resume

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/ConnectionManager.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4819
> Trigger refresh on app enter foreground

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/Chain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/RpcSource.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/TransactionSource.kt
- oneinchkit/src/main/java/io/horizontalsystems/oneinchkit/OneInchKit.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/TokenFactory.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/TradeManager.kt
> Add Avalanche chain

- app/build.gradle
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5257
> Update HdWallet dependency

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/core/Erc20TransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/contracts/ContractMethodFactories.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/decorations/UnknownTransactionDecoration.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/EthereumTransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/InternalTransactionSyncer.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionSyncManager.kt
- oneinchkit/src/main/java/io/horizontalsystems/oneinchkit/decorations/OneInchDecoration.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/decorations/SwapDecoration.kt
Handle input size < 4 in ContractMethodFactories
> Add `initial` flag for transaction syncers.

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/transactionsyncers/TransactionSyncManager.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5313
> Do not use main thread of observing

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/NftsViewModel.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/contracts/ContractEvent.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/core/Eip1155EventDecorator.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/core/Eip721EventDecorator.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/core/Extensions.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/core/NftKit.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/events/Eip1155TransferEventInstance.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/events/Eip721TransferEventInstance.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/models/Eip1155Event.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/models/Eip721Event.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/models/TokenInfo.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5391
> Implement `Eip721` and `Eip1155` transfer event decorators

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/addresswatch/AddressWatchViewModel.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/MainViewModel.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/RpcSource.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5600
> Remove BSC websocket

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/Chain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/RpcSource.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/TransactionSource.kt
- oneinchkit/src/main/java/io/horizontalsystems/oneinchkit/OneInchKit.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5725
> Add Gnosis blockchain

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/EtherscanService.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5860
> Fix fetching Arbitrum transactions from Cloudflare

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/Chain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/RpcSource.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/TransactionSource.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5939
> Add support for Fantom chain

- oneinchkit/src/main/java/io/horizontalsystems/oneinchkit/OneInchKit.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5939
> Add support for Fantom in OneInchKit

- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/PriceImpactManager.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6018
> Take best price as base instead of pool price

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/EtherscanService.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6052
> Fix fetching transactions

- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/UniswapV3Kit.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/pool/PoolManager.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/quoter/QuoteExactInputSingleMethod.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/quoter/QuoteExactOutputSingleMethod.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/quoter/QuoterV2.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/router/SwapRouter.kt
> Add support for PancakeSwap V3

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/Configuration.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/uniswapV3/UniswapV3ViewModel.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/UniswapV3Kit.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/models/DexType.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/pool/PoolManager.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/quoter/QuoterV2.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/router/SwapRouter.kt
> Add BSC support for Uniswap V3

- oneinchkit/src/main/java/io/horizontalsystems/oneinchkit/OneInchService.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6363
> Update 1inch Api url

- oneinchkit/src/main/java/io/horizontalsystems/oneinchkit/OneInchService.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6945
> Set path parameter before query parameters

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/EtherscanService.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7032
> Fix etherscan action name

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/decorations/UnknownTransactionDecoration.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7096
> Add address tags from internal transactions

- erc20kit/src/main/java/io/horizontalsystems/erc20kit/events/TransferEventInstance.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/events/Eip1155TransferEventInstance.kt
- nftkit/src/main/java/io/horizontalsystems/nftkit/events/Eip721TransferEventInstance.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7096
> Do not tag own address

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/Interfaces.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/TransactionManager.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/TransactionStorage.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/storage/TransactionTagDao.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7136
> Add method to get token contract addresses from transaction tags

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/Chain.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/RpcSource.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/TransactionSource.kt
- oneinchkit/src/main/java/io/horizontalsystems/oneinchkit/OneInchKit.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/TokenFactory.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/TradeManager.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/pool/PoolManager.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/quoter/QuoterV2.kt
- uniswapkit/src/main/java/io/horizontalsystems/uniswapkit/v3/router/SwapRouter.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7512
> Add chain Base

- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/addresswatch/AddressWatchViewModel.kt
- app/src/main/java/io/horizontalsystems/ethereumkit/sample/modules/main/MainViewModel.kt
- build.gradle
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/core/EthereumKit.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/TransactionSource.kt
- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/network/EtherscanService.kt
- gradle/wrapper/gradle-wrapper.properties
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7698
> Rotate keys

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/models/RpcSource.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7964
> Add polygon RPC source

- ethereumkit/src/main/java/io/horizontalsystems/ethereumkit/decorations/UnknownTransactionDecoration.kt
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/8198
> Fix tags for native token txs
